### ISSUE TITLE
Valid relative imports must include the ".js" file extension

### ISSUE THREAD

**Issue by beeman** [pikapkg/pack#11]
First of all great work on this project!! It looks very promising!

It seems that the `typescript-package` example causes an error when building:

```
/opt/app/pikapkg-examples/typescript-package # pack build
@pika/pack build v0.3.1
[1/7] Validating source...
[2/7] Preparing pipeline...
      ❇️  pkg/
[3/7] Running @pika/plugin-ts-standard-pkg...
      📝  pkg/dist-src/index.js [esnext]
      📝  pkg/dist-types/index.d.ts [types]
      » Linting with standard-pkg...

dist-src/index.js
  ⚠️  [4:0] "./foo": Valid relative imports must include the ".js" file extension.

1 standard-pkg errors found.
[4/7] Running @pika/plugin-build-node...
      📝  pkg/dist-node/index.js [main]
[5/7] Running @pika/plugin-build-web...
      📝  pkg/dist-web/index.js [module]
[6/7] Running @pika/plugin-build-deno...
[7/7] Finalizing package...
      📝  pkg/README.md
      📝  pkg/package.json
      📦  pkg/
Done in 4.57s.
```

In my own project this seems to stop the process: 

```
@pika/pack build v0.3.1
[1/5] Validating source...
[2/5] Preparing pipeline...
      ❇️  pkg/
[3/5] Running @pika/plugin-ts-standard-pkg...
      📝  pkg/dist-src/index.js [esnext]
      📝  pkg/dist-types/index.d.ts [types]
      » Linting with standard-pkg...

dist-src/beeman-fs-manager.js
  ⚠️  [2:0] "rxjs/operators": Avoid directly importing private files inside external packages.
  ⚠️  [3:0] "./utils": Valid relative imports must include the ".js" file extension.
dist-src/utils/index.js
  ⚠️  [1:0] "../config": Valid relative imports must include the ".js" file extension.

3 standard-pkg errors found.
[4/5] Running @pika/plugin-build-web...
Error: Could not resolve './utils' from pkg/dist-src/beeman-fs-manager.js
    at error (/opt/beeman/beeman-fs/node_modules/rollup/dist/rollup.js:3597:30)
    at /opt/beeman/beeman-fs/node_modules/rollup/dist/rollup.js:17500:25
```

**Comment by FredKSchott** [comment]
See this discussion here: https://github.com/pikapkg/builders/issues/3

**Comment by beeman** [comment]
Thanks @FredKSchott
