### ISSUE TITLE
Build seems to fail on YAML file

### ISSUE THREAD

**Issue by kapooostin** [pikapkg/pack#17]
Here is console output:
```console
@pika/pack build v0.3.2
[1/5] Validating source...
[2/5] Preparing pipeline...
      ❇️  pkg/
[3/5] Running @pika/plugin-standard-pkg...
SyntaxError: /Work/Dropbox/works/*****/src/__tests__/__data__/_config.yml: Unexpected token, expected ";" (6:18)

  4 |     month: 2
  5 |   bankImgPath: 'https://******/'
> 6 |   title: Рассылка Premium ******* | Февраль 2018
    |                   ^
```

The file is correct and it is inside excluded folder, why does `@pika/pack` even bother? Maybe it doesn't like Cyrillic?

**Comment by FredKSchott** [comment]
Interesting... can you share your `package.json` pipeline? Also, did a stack trace come with the error?

We pass that value to https://www.npmjs.com/package/glob 's exclude option, so I'm expecting something is causing it to not be excluded properly

**Comment by kapooostin** [comment]
I used pipeline from examples and it doesn't account for nested folders in `__tests__`. I changed `exclude` glob to `__tests__/**/*` and it solved the issue.

The stack trace was like this:
```console
at Parser.raise (*****/node_modules/standard-pkg/node_modules/@babel/parser/lib/index.js:3831:17)
at Parser.unexpected (*****/node_modules/standard-pkg/node_modules/@babel/parser/lib/index.js:5143:16)
at Parser.semicolon (*****/node_modules/standard-pkg/node_modules/@babel/parser/lib/index.js:5131:40)
at Parser.parseExpressionStatement (*****/node_modules/standard-pkg/node_modules/@babel/parser/lib/index.js:7781:10)
at Parser.parseStatementContent (*****/node_modules/standard-pkg/node_modules/@babel/parser/lib/index.js:7380:19)
at Parser.parseStatement (*****/node_modules/standard-pkg/node_modules/@babel/parser/lib/index.js:7248:17)
at Parser.parseLabeledStatement (*****/node_modules/standard-pkg/node_modules/@babel/parser/lib/index.js:7768:22)
at Parser.parseStatementContent (*****/node_modules/standard-pkg/node_modules/@babel/parser/lib/index.js:7378:19)
at Parser.parseStatement (*****/node_modules/standard-pkg/node_modules/@babel/parser/lib/index.js:7248:17)
at Parser.parseBlockOrModuleBlockBody (*****/node_modules/standard-pkg/node_modules/@babel/parser/lib/index.js:7812:25)
```

**Comment by biirus** [comment]
I have a same issue.
Here is the `package.json` settings:
```
 "@pika/pack": {
    "pipeline": [
      [
        "@pika/plugin-standard-pkg",
        {
          "exclude": [
            "src/components/**/test/*",
            "src/components/**/*.md"
          ]
        }
      ]
    ]
  }
```

And there is the error stack trace:
```
❯ pack build
@pika/pack build v0.3.2
[1/4] Validating source...
[2/4] Preparing pipeline...
      ❇️  pkg/
[3/4] Running @pika/plugin-standard-pkg...
SyntaxError: /Users/biirus/Projects/iburn/src/components/Avatar/readme.md: Unexpected character '#' (1:1)

> 1 | ### Image avatars
    |  ^
  2 | 
  3 | Image avatars can be created by passing standard img props `src` or `srcSet` into the component.
  4 | 
    at _class.raise (/Users/biirus/Projects/iburn/node_modules/@babel/parser/lib/index.js:4051:15)
    at _class.readToken_numberSign (/Users/biirus/Projects/iburn/node_modules/@babel/parser/lib/index.js:4390:12)
    at _class.getTokenFromCode (/Users/biirus/Projects/iburn/node_modules/@babel/parser/lib/index.js:4597:14)
    at _class.readToken (/Users/biirus/Projects/iburn/node_modules/@babel/parser/lib/index.js:4266:12)
    at _class.readToken (/Users/biirus/Projects/iburn/node_modules/@babel/parser/lib/index.js:3779:46)
    at _class.nextToken (/Users/biirus/Projects/iburn/node_modules/@babel/parser/lib/index.js:4258:12)
    at _class.parse (/Users/biirus/Projects/iburn/node_modules/@babel/parser/lib/index.js:8914:10)
    at parse (/Users/biirus/Projects/iburn/node_modules/@babel/parser/lib/index.js:10946:38)
    at parser (/Users/biirus/Projects/iburn/node_modules/@babel/core/lib/transformation/normalize-file.js:170:34)
    at normalizeFile (/Users/biirus/Projects/iburn/node_modules/@babel/core/lib/transformation/normalize-file.js:138:11)
```

**Comment by FredKSchott** [comment]
That's so strange. Updated all examples to use the more greedy "**/*". Thanks both of you for your help tracking this down!
