### ISSUE TITLE
Unexpected error when trying to build

### ISSUE THREAD

**Issue by mubaidr** [pikapkg/pack#27]
```bash
\node_modules\pump\index.js:69
});
 ^

SyntaxError: Unexpected token )
    at new Script (vm.js:85:7)
    at createScript (vm.js:266:10)
    at Object.runInThisContext (vm.js:314:10)
    at Module._compile (internal/modules/cjs/loader.js:698:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by FredKSchott** [comment]
This seems to be an issue with pump, but it looks like there hasn't been a new version of that package in about a year. What version of Node.js are you running on your machine?

**Comment by mubaidr** [comment]
Node: 11.6, all packages latest.

**Comment by FredKSchott** [comment]
So strange...

Sorry that you're hitting this issue but there's nothing we can do here. Closing this issue since it should really be filed in https://github.com/mafintosh/pump, if more people encounter this we can try version pinning the dependency or getting rid of it (by switching out `execa`)
