### ISSUE TITLE
Can't use subfolders in src?

### ISSUE THREAD

**Issue by varna** [pikapkg/pack#64]
Hi!

I wanted to order my stuff around in a neet way. So I separated and dropped 6 files into a sub-folder `src/units`. Now `pika build` errors out:
```bash
12 standard-pkg errors found.

[4/6] Running @pika/plugin-build-node...
Error: Could not resolve './units' from pkg/dist-src/findUnit.js
    at error (/Users/varna/Code/libs/measure-ts/node_modules/rollup/dist/rollup.js:9402:30)
    at ModuleLoader.handleMissingImports (/Users/varna/Code/libs/measure-ts/node_modules/rollup/dist/rollup.js:16414:17)
    at ModuleLoader.<anonymous> (/Users/varna/Code/libs/measure-ts/node_modules/rollup/dist/rollup.js:16465:26)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/varna/Code/libs/measure-ts/node_modules/rollup/dist/rollup.js:15450:28)
```

I know that source files should be in `src` folder. There's another issue for that. But does this mean that I cannot use sub-folders in `src`? Or there's a different problem in my project.

**Comment by FredKSchott** [comment]
If `units` is a folder, then you should import it by `'./units/index.js'`Resolving to the index.js file inside of a folder automatically is holdover from Common.js that will probably be removed in future versions of Node.

We should look into making this error message more clear.

**Comment by varna** [comment]
Yeah... I'm currently hitting table with my face to hide my shame... :D
Thanks for help!

I don't know if it's possible to make this error clearer. It's just that I got used to automatic import of index files...
